### ISSUE TITLE
Login superadmin fail

### ISSUE THREAD

**Issue by uesleycorrea** [jessequinn/magoware#2]
Hi! I make installation with the tutorial, all ok. But superadmin is not running. Logs:

POST /api/auth/login 200 2 - 5.538 ms
app_1      | error: Finding the user failed with error:  message=groups is not associated to users!, stack=Error: groups is not associated to users!

**Comment by uesleycorrea** [comment]
In the adminer, I not find tables in magoware database. I access the magoware container and run the command db:migrate. This is the log:


Loaded configuration file "config/env/db.connection.js".

ERROR: connect ECONNREFUSED 172.18.0.3:3309

**Comment by uesleycorrea** [comment]
I try telnet in this address and port from Linux with docker but not access (refused). And changed the address from the 172.18.0.1:3309 and telnet ready. I change the port about the other container expose this default Mysql port.

**Comment by jessequinn** [comment]
i’ll get back to you on this.

**Comment by jessequinn** [comment]
I think the issue is that you need to run the configuration setup for the db. So basically do not use the db.configuration file and setup the DB only. It will give an error on Redis. Afterwards you can move back the db.configuration that I included.

**Comment by jessequinn** [comment]
I have included a new installation procedure. I just tested it myself and it works.
